### ISSUE TITLE
Why mysqlclient-sys does not provide mysql_ssl_mode enum?

### ISSUE THREAD

**Issue by p-alik** [sgrif/mysqlclient-sys#27]
Both [bindings_windows.rs](https://github.com/sgrif/mysqlclient-sys/blob/a1ef27b075df6d6c6f760554c94b9860ca9e7c24/src/bindings_windows.rs#L1444) and [bindings_macos.rs](https://github.com/sgrif/mysqlclient-sys/blob/a1ef27b075df6d6c6f760554c94b9860ca9e7c24/src/bindings_macos.rs#L678) provide  `MYSQL_OPT_SSL_MODE` variant in `mysql_option` enum. But only `bindings_macos.rs` offers values for the option in form of [mysql_ssl_mode](https://github.com/sgrif/mysqlclient-sys/blob/a1ef27b075df6d6c6f760554c94b9860ca9e7c24/src/bindings_macos.rs#L791) enum.

There is no word in [mysql_options](https://dev.mysql.com/doc/c-api/8.0/en/mysql-options.html) documentation about any Windows incapability according `MYSQL_OPT_SSL_MODE`.
Would it be possible to add `mysql_ssl_mode` enum into `bindings_windows.rs` also?

**Comment by pjenvey** [comment]
@weiznich, this was fixed by #28 and can now be closed.

**Comment by weiznich** [comment]
:+1:
