### ISSUE TITLE
Bundling support

### ISSUE THREAD

**Issue by nico-abram** [sgrif/mysqlclient-sys#30]
At least for windows, I think this might be pretty nice to have (Since for many people building and configuring can be a PITA). I mean something similar to what [libsqlite3-sys does](https://github.com/rusqlite/rusqlite#notes-on-building-rusqlite-and-libsqlite3-sys) (Just compile the library in the build step)

If this is out of scope or wont-fix for some reason I apologize (A quick glance a the issue tracker did not show duplicates)

I'm not a diesel or pq-sys user myself but [all the discussion in diesel's tracker](https://github.com/diesel-rs/diesel/issues/487) made me think this might be desireable (To eventually maybe have a bundling feature in diesel and diesel cli)

A [quick](https://github.com/sgrif/mysqlclient-sys/issues/22) [glance](https://github.com/sgrif/mysqlclient-sys/issues/5) at the issue tracker showed multiple issues about confusion or problems w.r.t building on windows

**Comment by weiznich** [comment]
Implemented in #39
