### ISSUE TITLE
Run failed with STATUS_DLL_NOT_FOUND

### ISSUE THREAD

**Issue by lazytiger** [sgrif/mysqlclient-sys#33]
I installed libmysql with vcpkg, and my application compiles, but it fails with message
```rust
error: process didn't exit successfully: `target\release\demo.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
```
I can't figure out why, and I tried ldd it doesn't show libmysql.dll

**Comment by miaomiao1992** [comment]
please add the path of mysql dll to the system variable.

**Comment by weiznich** [comment]
Closed as this is a setup error in the user environment.
