### ISSUE TITLE
Cargo build on Windows 7 target msvc

### ISSUE THREAD

**Issue by dkislov** [sgrif/mysqlclient-sys#5]
I cloned repository and tried to build locally: cargo build --verbose. Got error: "error: could not find native static library `mysqlclient`, perhaps an -L flag is missing?". To solve it I changed in build.rs line 24:
println!("cargo:rustc-link-lib=static=libmysql"); <===== libmysql instead of mysqlclient.

Is that bug or somehow could be configured?

**Comment by itsnotvalid** [comment]
Stuck on this because libmysqlclient/libmysql doesn't build with ming64 as well. I can only use VC ABI and the package names are just different with vcpkg.

**Comment by SingingBush** [comment]
I guess this is still a problem:

```
Compiling mysqlclient-sys v0.2.3
     Running `rustc --crate-name mysqlclient_sys C:\Users\singingbush\.cargo\registry\src\github.com-1ecc6299db9ec823\mysqlclient-sys-0.2.3\src\lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=14ffe003dec73a57 -C extra-filename=-14ffe003dec73a57 --out-dir C:\projects\rwp\target\debug\deps -L dependency=C:\projects\rwp\target\debug\deps --cap-lints allow -l static=mysqlclient`
```

**Comment by jwwb681232** [comment]
I have the same problem

**Comment by dten** [comment]
for me i fixed this by moving the `vcpkg` check first as it was able to correctly find the libraries

**Comment by itsnotvalid** [comment]
@dten can you post your modifications here so we can check? Thanks

**Comment by dten** [comment]
Hey sorry I actually ended up with no changes. Setting the environment variable to static link the CRT sort it for me. Not ideal but it works

**Comment by dten** [comment]
actually i tell a lie, i was using my fork and didn't realise it. reverting to the release one resulting in not being able to build. I ended up with cargo/.config specifying

```[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
```
and using a fork with this change
https://github.com/dten/mysqlclient-sys/commit/615b69c97783eb8676d3e620df459af243ab2ed5

**Comment by weiznich** [comment]
I'm closing this as we now have a CI setup that demonstrates that building and linking works on windows.
