### ISSUE TITLE
Can't i configure my libmysql.dll file path?

### ISSUE THREAD

**Issue by moxiangli** [sgrif/mysqlclient-sys#7]
When i installed mysql, can't i configure my libmysql.dll file path? if use vcpkg install libmysql:x64-windows command, it seems that mysql will be installed on my system again. Can somebody give me some helps?

**Comment by Eijebong** [comment]
The README says that:
> - First, it will attempt to use pkg-config to locate it. All the config options, such as PKG_CONFIG_ALLOW_CROSS, PKG_CONFIG_ALL_STATIC etc., of the crate pkg-config apply.
   
> - MSVC ABI builds will then check for a Vcpkg installation using the vcpkg cargo build helper. Set the VCKPG_ROOT environment variable to point to your Vcpkg installation and run vcpkg install libmysql:x64-windows to install the required libraries.

>    - If the library cannot be found using pkg-config, it will invoke the command mysql_config --variable=pkglibdir

And the documentation from pkg-config says that setting `FOO_NO_PKG_CONFIG` will disable pkg-config. I think it should solve your issue

**Comment by moxiangli** [comment]
I got an error when i compiling after running vcpkg install libmysql:x64-windows:
   Compiling mysqlclient-sys v0.2.3
error: could not find native static library `mysqlclient`, perhaps an -L flag is missing?
what shuld i do ?

**Comment by Eijebong** [comment]
Is your `VCKPG_ROOT` environment variable set ? Is mysql present in the directory pointed by this variable ?

**Comment by moxiangli** [comment]
Thank you for your help.
But which directory VCKPG_ROOT shuld pointed? Directory of vcpkg.exe or libmysql.lib?
I installed mysql lib with vcpkg install libmysql:x64-windows command. I can find libmysql.lib file
in C:\App\Vcpackage\vcpkg-master\installed\x64-windows\lib.  vcpkg.exe is in directory C:\App\Vcpackage\vcpkg-master.
I installed mysql in some ather directory.
My english is poor. i don't know whether i have explained it  clearly.

**Comment by Eijebong** [comment]
I have no idea :D I don't know anything about how building rust apps (or anything else...) on windows.

If I understand correctly, `VCKPG_ROOT` is a variable you have to set before installing but it should probably work without it...

https://docs.rs/vcpkg/0.2.2/vcpkg/ The documentation here gives some commands to check what paths are used for a library, you can play with environment variables and check the mysql .lib file that is detected by vcpkg.

**Comment by moxiangli** [comment]
Ok, thank you very match. i'll try to compile it on unix latter. But i think this project shuld think about running on windows a little more.

**Comment by Eijebong** [comment]
Well it definitely works on windows
Also I didn't think about looking there, but https://github.com/sgrif/mysqlclient-sys/blob/master/.appveyor.yml#L7 here it's defining `MYSQLCLIENT_LIB_DIR` which seems to be what you want

**Comment by elycruz** [comment]
Thanks for due diligence @Eijebong (`MYSQLCLIENT_LIB_DIR` worked for me!) 👍 .
