### ISSUE TITLE
Static linking of libmysqlclient

### ISSUE THREAD

**Issue by Emulator000** [sgrif/mysqlclient-sys#9]
How I can static link the library in order to not require the installation of "libmysqlclient.so.20" in other machines?

I tried compiling with x86_64-unknown-linux-musl without luck.

**Comment by sgrif** [comment]
That's going to depend heavily on your setup. Are you using pkg-config or mysql_config? Do you have the correct version of mysqlclient installed on your machine compiled for static linking? You mentioned you're trying to use musl -- Did you compile mysql from source against musl?

**Comment by Emulator000** [comment]
Actually I managed to resolve adding a "build.rs" file with this content:
```
fn main() {
    println!(r"cargo:rustc-link-lib=static=mysqlclient");
    println!(r"cargo:rustc-link-lib=static=stdc++");
    println!(r"cargo:rustc-link-lib=static=z");
}
```

**Comment by BlackDex** [comment]
@Emulator000 And on which OS are you building this? With which dev libraries installed?

**Comment by Emulator000** [comment]
@BlackDex I'm bulding it on Ubuntu 20.04 LTS with `libmysqlclient-dev` installed, I think that `libmariadb-dev` it's okay too.

You can see a compiled binary in this way here: https://github.com/facile-it/rabbitmq-consumer/releases/tag/v1.0.3
